[package]
name = "rustieee"
version = "0.1.0"
edition = "2021"

[features]
ufmt = ["dep:ufmt"]
ieee802154 = []

[dependencies]
thiserror-no-std = "2.0.2"
ufmt = { version = "0.2.0", optional = true }
