[package]
name = "rustieee"
version = "0.1.0"
edition = "2021"

[features]
ufmt = ["dep:ufmt"]
ieee802154 = []

[dependencies]
heapless = { version = "0.7.16", features = ["ufmt-impl"] }
thiserror-no-std = "2.0.2"
ufmt = { version = "0.2.0", optional = true }
byte = "0.2.6"
